### ISSUE TITLE
Make name of gitrepository and kustomization created by the oprator configurable

### ISSUE THREAD

**Issue by monotek** [controlplaneio-fluxcd/flux-operator#122]
When i use the FluxInstance definition the operator creates a gitrepositiry and a kustomization with the name "flux-system". It would be nice these names would be configurable.

In our current bootstrapped setup we named them "cluster" and have a "flux-system" kustomization which handles the actual flux-system namespace,

**Comment by stefanprodan** [comment]
We could add `.spec.sync.name` as an optional field that defaults to the instance namespace when not set. Just need to check all the code and make sure that there is no place where the operator uses the namespace name to query the cluster for the sync status.

**Comment by stefanprodan** [comment]
After implementing the sync name customisation, I realise that this is the perfect way to shoot yourself in the foot. Changing the sync name after a FluxInstance is created, will wipe clean you cluster since the old Kustomization GC will trigger the deletion of all managed resources. Another way to mess up everything, is by setting the name when migrating a cluster from `flux bootstrap` and you'll have two root Kustomizations fighting over the cluster state.

I really wish people would use the conventions we've set in upstream and not roll their own custom bootstrap like you did. Anyway I'm not going to fight this, if you mess with the sync name then you should be aware of the side-effects.

**Comment by stefanprodan** [comment]
I figured out how to enforce immutability for this field in the CRD using CEL, so I feel less worried about exposing this option.

**Comment by monotek** [comment]
Many thanks for the quick implementation ❤️
